[package]
name = "sharktells_shared"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.141"
bincode = { version = "2.0.1", features = ["serde"] }
rust_decimal = { version = "1.39.0", features = ["serde", "std"] }